### ISSUE TITLE
Create Test Connection between Student Backend and Indy Pool

### ISSUE THREAD

**Issue by PJUllrich** [Quintor/StudyBits#24]
Preferably running the backend locally and the pool in docker containers.
Alternatively, running the backend and the pool nodes all as docker containers.

**Comment by pimotte** [comment]
Imho, the second is a must-have, and the first one is nice to have, maybe must-have because we can save tons of development time with it. 

In case you're running into trouble with the docker stuff, but you manage to get it to run locally, just let me know and I could pick up the docker part.

Related to #19

**Comment by PJUllrich** [comment]
Created the `docker-compose-run-pool` file, which runs the Indy-Pool independently of the backends. The student backend can connect to it. Tested locally, not with backend as Docker container.
